### ISSUE TITLE
Penambahan Menu Organisasi di Rapor Semester

### ISSUE THREAD

**Issue by Muham-NFBSB** [OpenThinkLabs/OpenThinkSASTickets#628]
Salam.
Penambahan pengisian nilai organisasi untuk rapor SMPIT NFBS Bogor

**Comment by wildanm** [comment]
@Muham-NFBSB  

Untuk pengisian nilai organisasi sudah ada kan ? di menu : Akademik --> Nilai --> Nilai Rapor --> Organisasi. 

<img width="1209" alt="Screen Shot 2020-12-05 at 00 08 25" src="https://user-images.githubusercontent.com/462398/101192849-440eab00-368e-11eb-950b-5d2a8e620162.png">
